export const projects = [
  {
    id: 1,
    title: "This website",
    description: "Feel free to check out how I developed this website",
    altImage: "Pasquale De Lucia picture",
    image: "/Pako.jpg",
    action: "Check code",
    type: "Qwik",
    color: "orange-600",
    href: "https://github.com/VarPDev/pako",
  },
  {
    id: 2,
    title: "Rick & Morty",
    description:
      "Wiki about Rick and Morty, an adult animated science fiction sitcom",
    altImage: "rick and morty",
    image: "/rick_and_morty.png",
    action: "Try it",
    type: "Angular",
    color: "orange-600",
    href: "https://rick-and-morty-e.web.app/",
  },
  {
    id: 3,
    title: "Resume me",
    description: "An app built with Flutter to share your own resume",
    altImage: "Resume me app logo",
    image: "/resume_me.png",
    action: "Download",
    type: "APP",
    color: "orange-600",
    href: "https://play.google.com/store/apps/details?id=com.pako.resume_me&pli=1",
  },
  {
    id: 4,
    title: "Tab sync",
    description:
      "Npm library that allows you to communicate between multiple browser tabs",
    altImage: "Tab sync logo",
    // image: "/rick_and_morty.png",
    action: "Try it",
    type: "NPM",
    color: "orange-600",
    href: "https://www.npmjs.com/package/@devhobby/tab-sync",
  },
];
